name: Boost

on:
  - push

jobs:
  ubuntu-18:
    runs-on: ubuntu-18.04
    steps:
    - name: env
      run: export
    - name: ls
      run: ls /opt/hostedtoolcache/boost || true
#   - name: apt clang
#     run: |
#       sudo apt-add-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main'
#       sudo apt-get update
#       apt-cache search ^clang
    - name: set-env
      run: |
        echo $BOOST_ROOT_1_72_0
        echo "::set-env name=BOOST_ROOT::$BOOST_ROOT_1_72_0"
        echo $BOOST_ROOT
        echo "::set-env name=foo::$HOME"
        echo $foo
        printenv foo


#  ubuntu-20:
#    runs-on: ubuntu-20.04
#    steps:
#    - name: env
#      run: export
#    - name: ls
#      run: ls /opt/hostedtoolcache/boost || true
#    - name: apt clang
#      run: |
#        sudo apt-add-repository 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal main'
#        sudo apt-get update
#        apt-cache search ^clang
